# Generated by Django 3.1.7 on 2021-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_class', '0003_auto_20210322_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='class_from',
            new_name='class_name',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
