# Generated by Django 3.1.7 on 2021-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_class', '0004_auto_20210322_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='is_active',
            field=models.IntegerField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='1->Active, 0->Inactive', null=True),
        ),
    ]
