# Generated by Django 3.1.7 on 2021-03-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_class', '0005_studentinfo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(1, 'Active'), (0, 'Inactive')], default=0, help_text='1->Active, 0->Inactive', null=True),
        ),
    ]
